version: '3.9'
services:
  db:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=my_password"
      - "MYSQL_DATABASE=my_database"
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - "PMA_HOST=db"
      - "MYSQL_ROOT_PASSWORD=my_password"
    ports:
      - 8080:80
    depends_on: 
      - db